version: '3.1'

services:

  db:
    image: mdillon/postgis
    environment:
      POSTGRES_PASSWORD: smartLifePath123
      POSTGRES_USER: postgres
      POSTGRES_DB: smart-path-life
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
